### ISSUE TITLE
Create a link on arxiv.org

### ISSUE THREAD

**Issue by MatthieuBizien** [eladrich/ScholarWithCode#2]
Hi @eladrich, very good extension idea! I browser arxiv a lot more than Google Scholar, would it be possible to add links to the implementations there too? 

https://chrome.google.com/webstore/detail/arxiv-vanity-plugin/jfnlkegibnoaagfdabjkchhocdhnoofk?hl=en does it for arxiv-vanity, it could be an inspiration.

semanticscholar.org would be great too.

**Comment by eladrich** [comment]
Thanks! Interesting idea, I'm debating whether I want to keep it focused only on Google Scholar or indeed extend it to other sites.

At the moment you're welcome to fork the project and change it to work with arxiv, you'll see that the code is very simple. You can then simply install the extension locally even without uploading it to the store.

**Comment by idow09** [comment]
#3

**Comment by idow09** [comment]
@MatthieuBizien  see PR #3

**Comment by MatthieuBizien** [comment]
Nice, thanks!
